# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake.bd
# Block Designs: The module: 'snake' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/snake_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_microblaze_0_0 || ORIG_REF_NAME==snake_microblaze_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mdm_1_0/snake_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_mdm_1_0 || ORIG_REF_NAME==snake_mdm_1_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_clk_wiz_1_0 || ORIG_REF_NAME==snake_clk_wiz_1_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_clk_wiz_1_100M_0/snake_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==snake_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_uartlite_0_0 || ORIG_REF_NAME==snake_axi_uartlite_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_axi_periph_0/snake_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_microblaze_0_axi_periph_0 || ORIG_REF_NAME==snake_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_dlmb_v10_0/snake_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_dlmb_v10_0 || ORIG_REF_NAME==snake_dlmb_v10_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_ilmb_v10_0/snake_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_ilmb_v10_0 || ORIG_REF_NAME==snake_ilmb_v10_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_dlmb_bram_if_cntlr_0/snake_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==snake_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_ilmb_bram_if_cntlr_0/snake_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==snake_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_lmb_bram_0/snake_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_lmb_bram_0 || ORIG_REF_NAME==snake_lmb_bram_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_gpio_0_0 || ORIG_REF_NAME==snake_axi_gpio_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_gpio_1_0 || ORIG_REF_NAME==snake_axi_gpio_1_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_gpio_2_0 || ORIG_REF_NAME==snake_axi_gpio_2_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_intc_0_0 || ORIG_REF_NAME==snake_axi_intc_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_xlconcat_0_0/snake_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_xlconcat_0_0 || ORIG_REF_NAME==snake_xlconcat_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_timer_0_0/snake_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_timer_0_0 || ORIG_REF_NAME==snake_axi_timer_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_tft_0_0/snake_axi_tft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_tft_0_0 || ORIG_REF_NAME==snake_axi_tft_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_mig_7series_0_0 || ORIG_REF_NAME==snake_mig_7series_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_mig_7series_0_81M_0/snake_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==snake_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_xbar_0/snake_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_xbar_0 || ORIG_REF_NAME==snake_xbar_0} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_7/snake_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_7 || ORIG_REF_NAME==snake_auto_pc_7} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_us_0 || ORIG_REF_NAME==snake_auto_us_0} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_us_1 || ORIG_REF_NAME==snake_auto_us_1} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_us_2 || ORIG_REF_NAME==snake_auto_us_2} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_0 || ORIG_REF_NAME==snake_auto_ds_0} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_0/snake_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_0 || ORIG_REF_NAME==snake_auto_pc_0} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_1 || ORIG_REF_NAME==snake_auto_ds_1} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_1/snake_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_1 || ORIG_REF_NAME==snake_auto_pc_1} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_2 || ORIG_REF_NAME==snake_auto_ds_2} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_2/snake_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_2 || ORIG_REF_NAME==snake_auto_pc_2} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_3 || ORIG_REF_NAME==snake_auto_ds_3} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_3/snake_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_3 || ORIG_REF_NAME==snake_auto_pc_3} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_4 || ORIG_REF_NAME==snake_auto_ds_4} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_4/snake_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_4 || ORIG_REF_NAME==snake_auto_pc_4} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_5 || ORIG_REF_NAME==snake_auto_ds_5} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_5/snake_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_5 || ORIG_REF_NAME==snake_auto_pc_5} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_6 || ORIG_REF_NAME==snake_auto_ds_6} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_6/snake_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_6 || ORIG_REF_NAME==snake_auto_pc_6} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_cc_0 || ORIG_REF_NAME==snake_auto_cc_0} -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/snake_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_microblaze_0_0 || ORIG_REF_NAME==snake_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/snake_microblaze_0_0_ooc_debug.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mdm_1_0/snake_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_mdm_1_0 || ORIG_REF_NAME==snake_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mdm_1_0/snake_mdm_1_0_ooc_trace.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_clk_wiz_1_0 || ORIG_REF_NAME==snake_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_clk_wiz_1_0 || ORIG_REF_NAME==snake_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_clk_wiz_1_100M_0/snake_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==snake_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_clk_wiz_1_100M_0/snake_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==snake_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_uartlite_0_0 || ORIG_REF_NAME==snake_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_uartlite_0_0 || ORIG_REF_NAME==snake_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_dlmb_v10_0/snake_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_dlmb_v10_0 || ORIG_REF_NAME==snake_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_ilmb_v10_0/snake_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_ilmb_v10_0 || ORIG_REF_NAME==snake_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_lmb_bram_0/snake_lmb_bram_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_0_0 || ORIG_REF_NAME==snake_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_0_0 || ORIG_REF_NAME==snake_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_1_0 || ORIG_REF_NAME==snake_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_1_0 || ORIG_REF_NAME==snake_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_2_0 || ORIG_REF_NAME==snake_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_2_0 || ORIG_REF_NAME==snake_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_intc_0_0 || ORIG_REF_NAME==snake_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_intc_0_0 || ORIG_REF_NAME==snake_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_timer_0_0/snake_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_timer_0_0 || ORIG_REF_NAME==snake_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_timer_0_0/snake_axi_timer_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_tft_0_0/snake_axi_tft_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_tft_0_0 || ORIG_REF_NAME==snake_axi_tft_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_tft_0_0/snake_axi_tft_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_tft_0_0 || ORIG_REF_NAME==snake_axi_tft_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0/user_design/constraints/snake_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_mig_7series_0_0 || ORIG_REF_NAME==snake_mig_7series_0_0} -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0/user_design/constraints/snake_mig_7series_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_mig_7series_0_0 || ORIG_REF_NAME==snake_mig_7series_0_0} -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_mig_7series_0_81M_0/snake_rst_mig_7series_0_81M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==snake_rst_mig_7series_0_81M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_mig_7series_0_81M_0/snake_rst_mig_7series_0_81M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==snake_rst_mig_7series_0_81M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_7/snake_auto_pc_7_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_us_0 || ORIG_REF_NAME==snake_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_us_1 || ORIG_REF_NAME==snake_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_us_2 || ORIG_REF_NAME==snake_auto_us_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_0 || ORIG_REF_NAME==snake_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_0/snake_auto_pc_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_1 || ORIG_REF_NAME==snake_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_1/snake_auto_pc_1_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_2 || ORIG_REF_NAME==snake_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_2/snake_auto_pc_2_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_3 || ORIG_REF_NAME==snake_auto_ds_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_3/snake_auto_pc_3_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_4 || ORIG_REF_NAME==snake_auto_ds_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_4/snake_auto_pc_4_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_5 || ORIG_REF_NAME==snake_auto_ds_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_5/snake_auto_pc_5_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_6 || ORIG_REF_NAME==snake_auto_ds_6} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_6/snake_auto_pc_6_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_cc_0 || ORIG_REF_NAME==snake_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0_ooc.xdc

# XDC: F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'snake'. Do not add the DONT_TOUCH constraint.

# Block Designs: F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake.bd
# Block Designs: The module: 'snake' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/snake_microblaze_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_microblaze_0_0 || ORIG_REF_NAME==snake_microblaze_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mdm_1_0/snake_mdm_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_mdm_1_0 || ORIG_REF_NAME==snake_mdm_1_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_clk_wiz_1_0 || ORIG_REF_NAME==snake_clk_wiz_1_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_clk_wiz_1_100M_0/snake_rst_clk_wiz_1_100M_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==snake_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_uartlite_0_0 || ORIG_REF_NAME==snake_axi_uartlite_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_axi_periph_0/snake_microblaze_0_axi_periph_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_microblaze_0_axi_periph_0 || ORIG_REF_NAME==snake_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_dlmb_v10_0/snake_dlmb_v10_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_dlmb_v10_0 || ORIG_REF_NAME==snake_dlmb_v10_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_ilmb_v10_0/snake_ilmb_v10_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_ilmb_v10_0 || ORIG_REF_NAME==snake_ilmb_v10_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_dlmb_bram_if_cntlr_0/snake_dlmb_bram_if_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==snake_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_ilmb_bram_if_cntlr_0/snake_ilmb_bram_if_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==snake_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_lmb_bram_0/snake_lmb_bram_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_lmb_bram_0 || ORIG_REF_NAME==snake_lmb_bram_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_gpio_0_0 || ORIG_REF_NAME==snake_axi_gpio_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_gpio_1_0 || ORIG_REF_NAME==snake_axi_gpio_1_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_gpio_2_0 || ORIG_REF_NAME==snake_axi_gpio_2_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_intc_0_0 || ORIG_REF_NAME==snake_axi_intc_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_xlconcat_0_0/snake_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_xlconcat_0_0 || ORIG_REF_NAME==snake_xlconcat_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_timer_0_0/snake_axi_timer_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_timer_0_0 || ORIG_REF_NAME==snake_axi_timer_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_tft_0_0/snake_axi_tft_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_axi_tft_0_0 || ORIG_REF_NAME==snake_axi_tft_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_mig_7series_0_0 || ORIG_REF_NAME==snake_mig_7series_0_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_mig_7series_0_81M_0/snake_rst_mig_7series_0_81M_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==snake_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: F:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_xbar_0/snake_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_xbar_0 || ORIG_REF_NAME==snake_xbar_0} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_7/snake_auto_pc_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_7 || ORIG_REF_NAME==snake_auto_pc_7} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_us_0 || ORIG_REF_NAME==snake_auto_us_0} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_us_1 || ORIG_REF_NAME==snake_auto_us_1} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_us_2 || ORIG_REF_NAME==snake_auto_us_2} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_0 || ORIG_REF_NAME==snake_auto_ds_0} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_0/snake_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_0 || ORIG_REF_NAME==snake_auto_pc_0} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_1 || ORIG_REF_NAME==snake_auto_ds_1} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_1/snake_auto_pc_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_1 || ORIG_REF_NAME==snake_auto_pc_1} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_2 || ORIG_REF_NAME==snake_auto_ds_2} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_2/snake_auto_pc_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_2 || ORIG_REF_NAME==snake_auto_pc_2} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_3 || ORIG_REF_NAME==snake_auto_ds_3} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_3/snake_auto_pc_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_3 || ORIG_REF_NAME==snake_auto_pc_3} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_4 || ORIG_REF_NAME==snake_auto_ds_4} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_4/snake_auto_pc_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_4 || ORIG_REF_NAME==snake_auto_pc_4} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_5 || ORIG_REF_NAME==snake_auto_ds_5} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_5/snake_auto_pc_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_5 || ORIG_REF_NAME==snake_auto_pc_5} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_ds_6 || ORIG_REF_NAME==snake_auto_ds_6} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_6/snake_auto_pc_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_pc_6 || ORIG_REF_NAME==snake_auto_pc_6} -quiet] -quiet

# IP: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_auto_cc_0 || ORIG_REF_NAME==snake_auto_cc_0} -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/snake_microblaze_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_microblaze_0_0 || ORIG_REF_NAME==snake_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/snake_microblaze_0_0_ooc_debug.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mdm_1_0/snake_mdm_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_mdm_1_0 || ORIG_REF_NAME==snake_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mdm_1_0/snake_mdm_1_0_ooc_trace.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_clk_wiz_1_0 || ORIG_REF_NAME==snake_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_clk_wiz_1_0 || ORIG_REF_NAME==snake_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_clk_wiz_1_100M_0/snake_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==snake_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_clk_wiz_1_100M_0/snake_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==snake_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_uartlite_0_0 || ORIG_REF_NAME==snake_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_uartlite_0_0 || ORIG_REF_NAME==snake_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_dlmb_v10_0/snake_dlmb_v10_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_dlmb_v10_0 || ORIG_REF_NAME==snake_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_ilmb_v10_0/snake_ilmb_v10_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_ilmb_v10_0 || ORIG_REF_NAME==snake_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_lmb_bram_0/snake_lmb_bram_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_0_0 || ORIG_REF_NAME==snake_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_0_0 || ORIG_REF_NAME==snake_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_1_0 || ORIG_REF_NAME==snake_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_1_0 || ORIG_REF_NAME==snake_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_2_0 || ORIG_REF_NAME==snake_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_gpio_2_0 || ORIG_REF_NAME==snake_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_intc_0_0 || ORIG_REF_NAME==snake_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_intc_0_0 || ORIG_REF_NAME==snake_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_timer_0_0/snake_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_timer_0_0 || ORIG_REF_NAME==snake_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_timer_0_0/snake_axi_timer_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_tft_0_0/snake_axi_tft_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_tft_0_0 || ORIG_REF_NAME==snake_axi_tft_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_tft_0_0/snake_axi_tft_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_axi_tft_0_0 || ORIG_REF_NAME==snake_axi_tft_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0/user_design/constraints/snake_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_mig_7series_0_0 || ORIG_REF_NAME==snake_mig_7series_0_0} -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0/user_design/constraints/snake_mig_7series_0_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_mig_7series_0_0 || ORIG_REF_NAME==snake_mig_7series_0_0} -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_mig_7series_0_81M_0/snake_rst_mig_7series_0_81M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==snake_rst_mig_7series_0_81M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_mig_7series_0_81M_0/snake_rst_mig_7series_0_81M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==snake_rst_mig_7series_0_81M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_7/snake_auto_pc_7_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_us_0 || ORIG_REF_NAME==snake_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_us_1 || ORIG_REF_NAME==snake_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_us_2 || ORIG_REF_NAME==snake_auto_us_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_0 || ORIG_REF_NAME==snake_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_0/snake_auto_pc_0_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_1 || ORIG_REF_NAME==snake_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_1/snake_auto_pc_1_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_2 || ORIG_REF_NAME==snake_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_2/snake_auto_pc_2_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_3 || ORIG_REF_NAME==snake_auto_ds_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_3/snake_auto_pc_3_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_4 || ORIG_REF_NAME==snake_auto_ds_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_4/snake_auto_pc_4_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_5 || ORIG_REF_NAME==snake_auto_ds_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_5/snake_auto_pc_5_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_ds_6 || ORIG_REF_NAME==snake_auto_ds_6} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_6/snake_auto_pc_6_ooc.xdc

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==snake_auto_cc_0 || ORIG_REF_NAME==snake_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0_ooc.xdc

# XDC: F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'snake'. Do not add the DONT_TOUCH constraint.
