# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/snake_1/snake_1.cache/wt [current_project]
set_property parent.project_path F:/snake_1/snake_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {E:/vivado/Vivado/2019.1/data/boards/board_files/nexys4_ddr} [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo f:/snake_1/snake_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake.bd
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/snake_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/snake_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mdm_1_0/snake_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mdm_1_0/snake_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_clk_wiz_1_0/snake_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_clk_wiz_1_100M_0/snake_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_clk_wiz_1_100M_0/snake_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_uartlite_0_0/snake_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_dlmb_v10_0/snake_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_ilmb_v10_0/snake_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_lmb_bram_0/snake_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_0_0/snake_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_1_0/snake_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_gpio_2_0/snake_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_intc_0_0/snake_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_timer_0_0/snake_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_timer_0_0/snake_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_tft_0_0/snake_axi_tft_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_axi_tft_0_0/snake_axi_tft_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0/user_design/constraints/snake_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0/user_design/constraints/snake_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_mig_7series_0_0/snake_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_mig_7series_0_81M_0/snake_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_rst_mig_7series_0_81M_0/snake_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_7/snake_auto_pc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_0/snake_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_1/snake_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_us_2/snake_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_0/snake_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_0/snake_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_1/snake_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_1/snake_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_2/snake_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_2/snake_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_3/snake_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_3/snake_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_4/snake_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_4/snake_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_5/snake_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_5/snake_auto_pc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_ds_6/snake_auto_ds_6_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_pc_6/snake_auto_pc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_auto_cc_0/snake_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/snake_1/snake_1.srcs/sources_1/bd/snake/ip/snake_microblaze_0_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top snake -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all snake_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef snake.dcp
create_report "snake_synth_1_synth_report_utilization_0" "report_utilization -file snake_utilization_synth.rpt -pb snake_utilization_synth.pb"

if { [catch {
  file copy -force F:/snake_1/snake_1.runs/snake_synth_1/snake.dcp F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir F:/snake_1/snake_1.ip_user_files/bd/snake]} {
  catch { 
    file copy -force F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_stub.v F:/snake_1/snake_1.ip_user_files/bd/snake
  }
}

if {[file isdir F:/snake_1/snake_1.ip_user_files/bd/snake]} {
  catch { 
    file copy -force F:/snake_1/snake_1.srcs/sources_1/bd/snake/snake_stub.vhdl F:/snake_1/snake_1.ip_user_files/bd/snake
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
